apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  appsettings.json: |-
    {
    "App": {
        "SelfUrl": "{{ .Values.config.selfUrl }}"
    },
    "AuthServer": {
        "Authority": "{{ .Values.config.authServer.authority }}",
        "ClientId": "MyProjectName_Blazor",
        "ResponseType": "{{ .Values.config.authServer.responseType }}"
    },
    "RemoteServices": {
        "Default": {
        "BaseUrl": "{{ .Values.config.gatewayUrl }}"
        },
        "AbpAccountPublic": {
        "BaseUrl": "{{ .Values.config.gatewayUrl }}"
        }
    },
    "AbpCli": {
        "Bundle": {
        "Mode": "BundleAndMinify",
        "Name": "global",
        "Parameters": {
            "LeptonTheme.Style": "Style6",
            "LeptonTheme.ChangeStyleDynamically": "true"
        }
        }
    }
    }
