# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: '$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
      - 'kind/feature'
  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
      - regression
      - 'kind/bug'
  - title: 📝 Documentation updates
    labels:
      - documentation
      - docs
      - doc
      - 'kind/doc'
  - title: 👻 Maintenance
    labels:
      - chore
      - dependencies
      - workflow
      - ci
      - perf
      - style
      - refactor
      - types
      - reverted
      - revert
      - 'kind/chore'
      - 'kind/dep'
  - title: 🚦 Tests
    labels:
      - test
      - tests
exclude-labels:
  - no-changelog
  - skip-changelog
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What’s Changed
  $CHANGES
Terms
Privacy
Security
