config:
    selfUrl: # https://myprojectname-st-administration
    corsOrigins: # https://myprojectname-st-gateway-web,https://myprojectname-st-gateway-public-web
    connectionStrings:
        administrationService: #
        saasService: #
    authServer:
        authority: # http://myprojectname-st-authserver
        requireHttpsMetadata: "false"
        swaggerClientId: WebGateway_Swagger
    remoteServices:
        abpIdentityBaseUrl: #
        useCurrentToken: "false"
    dotnetEnv: #
    redisHost: #
    rabbitmqHost: #
    elasticsearchUrl: #
    stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

synchedCommunication:
    authority: # https://myprojectname-st-authserver

ingress:
    host: # myprojectname-st-administration
    tlsSecret: myprojectname-tls

image:
    repository: mycompanyname/myprojectname-service-administration
    tag: latest
    pullPolicy: IfNotPresent

env: {}
