apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  ocelot.json: |-
    {
      "GlobalConfiguration": {
      "BaseUrl": "{{ .Values.config.globalConfigurationBaseUrl }}"
    },
      "Routes": [
    {
      "DownstreamPathTemplate": "/api/account/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.accountService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.accountService.host }}",
          "Port": {{ .Values.reRoutes.accountService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/account/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },    
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/identity/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/identity/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/openiddict/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/openiddict/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Identity Service",
      "DownstreamPathTemplate": "/api/account-admin/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.identityService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.identityService.host }}",
          "Port": {{ .Values.reRoutes.identityService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/account-admin/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Saas Service",
      "DownstreamPathTemplate": "/api/saas/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.saasService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.saasService.host }}",
          "Port": {{ .Values.reRoutes.saasService.port }}
        }
      ],
      "UpstreamPathTemplate": "/api/saas/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/abp/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/abp/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/audit-logging/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/audit-logging/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/language-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/language-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/text-template-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/text-template-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/feature-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/feature-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/permission-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/permission-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/setting-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/setting-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Administration Service",
      "DownstreamPathTemplate": "/api/lepton-theme-management/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.administrationService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.administrationService.host }}",
          "Port": "{{ .Values.reRoutes.administrationService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/lepton-theme-management/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    },
    {
      "ServiceKey": "Product Service",
      "DownstreamPathTemplate": "/api/product-service/{everything}",
      "DownstreamScheme": "{{ .Values.reRoutes.productService.schema }}",
      "DownstreamHostAndPorts": [
        {
          "Host": "{{ .Values.reRoutes.productService.host }}",
          "Port": "{{ .Values.reRoutes.productService.port }}",
        }
      ],
      "UpstreamPathTemplate": "/api/product-service/{everything}",
      "UpstreamHttpMethod": [ "Put", "Delete", "Get", "Post" ]
    }]
    }