// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.CmsKit.Public.Contact;

// ReSharper disable once CheckNamespace
namespace X.Abp.CmsKit.Public.Contact;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContactPublicAppService), typeof(ContactPublicClientProxy))]
public partial class ContactPublicClientProxy : ClientProxyBase<IContactPublicAppService>, IContactPublicAppService
{
    public virtual async Task SendMessageAsync(ContactCreateInput input)
    {
        await RequestAsync(nameof(SendMessageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ContactCreateInput), input }
        });
    }
}
