// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.CmsKit.Public.Faqs;

// ReSharper disable once CheckNamespace
namespace X.Abp.CmsKit.Public.Faqs;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IFaqSectionPublicAppService), typeof(FaqSectionPublicClientProxy))]
public partial class FaqSectionPublicClientProxy : ClientProxyBase<IFaqSectionPublicAppService>, IFaqSectionPublicAppService
{
    public virtual async Task<List<FaqSectionWithQuestionsDto>> GetListSectionWithQuestionsAsync(FaqSectionListFilterInput input)
    {
        return await RequestAsync<List<FaqSectionWithQuestionsDto>>(nameof(GetListSectionWithQuestionsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(FaqSectionListFilterInput), input }
        });
    }
}
