// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.CmsKit.Public.UrlShorting;

// ReSharper disable once CheckNamespace
namespace X.Abp.CmsKit.Public.UrlShorting;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUrlShortingPublicAppService), typeof(UrlShortingPublicClientProxy))]
public partial class UrlShortingPublicClientProxy : ClientProxyBase<IUrlShortingPublicAppService>, IUrlShortingPublicAppService
{
    public virtual async Task<ShortenedUrlDto> FindBySourceAsync(string source)
    {
        return await RequestAsync<ShortenedUrlDto>(nameof(FindBySourceAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), source }
        });
    }
}
