// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.CmsKit.Admin.Polls;

// ReSharper disable once CheckNamespace
namespace X.Abp.CmsKit.Admin.Polls;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPollAdminAppService), typeof(PollAdminClientProxy))]
public partial class PollAdminClientProxy : ClientProxyBase<IPollAdminAppService>, IPollAdminAppService
{
    public virtual async Task<PagedResultDto<PollDto>> GetListAsync(GetPollListInput input)
    {
        return await RequestAsync<PagedResultDto<PollDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetPollListInput), input }
        });
    }

    public virtual async Task<PollWithDetailsDto> GetAsync(Guid id)
    {
        return await RequestAsync<PollWithDetailsDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PollWithDetailsDto> CreateAsync(CreatePollDto input)
    {
        return await RequestAsync<PollWithDetailsDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreatePollDto), input }
        });
    }

    public virtual async Task<PollWithDetailsDto> UpdateAsync(Guid id, UpdatePollDto input)
    {
        return await RequestAsync<PollWithDetailsDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdatePollDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<PollWidgetDto>> GetWidgetsAsync()
    {
        return await RequestAsync<ListResultDto<PollWidgetDto>>(nameof(GetWidgetsAsync));
    }

    public virtual async Task<GetResultDto> GetResultAsync(Guid id)
    {
        return await RequestAsync<GetResultDto>(nameof(GetResultAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
