config:
    selfUrl: https://myprojectname-st-saas
    corsOrigins: https://myprojectname-st-gateway-web,https://myprojectname-st-gateway-public-web
    connectionStrings:
        administrationService: #
        saasService: #
    authServer:
        authority: # http://myprojectname-st-authserver
        requireHttpsMetadata: # "false"
    dotnetEnv: Staging
    redisHost: #
    rabbitmqHost: #
    elasticsearchUrl: #
    stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
    host: myprojectname-st-saas
    tlsSecret: myprojectname-tls

image:
    repository: abpvnext/myprojectname-service-saas
    tag: latest
    pullPolicy: IfNotPresent

env: {}
