// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.FileManagement.Files;

// ReSharper disable once CheckNamespace
namespace X.Abp.FileManagement.Files;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPublicFileDescriptorAppService), typeof(PublicFileDescriptorClientProxy))]
public partial class PublicFileDescriptorClientProxy : ClientProxyBase<IPublicFileDescriptorAppService>, IPublicFileDescriptorAppService
{
    public virtual async Task<RawFileDto> GetRawFileAsync(string name)
    {
        return await RequestAsync<RawFileDto>(nameof(GetRawFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetFileAsync(string name)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<UploadOutput> UploadAsync(UploadInput input)
    {
        return await RequestAsync<UploadOutput>(nameof(UploadAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UploadInput), input }
        });
    }
}
