// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.TextTemplateManagement.TextTemplates;

// ReSharper disable once CheckNamespace
namespace X.Abp.TextTemplateManagement.TextTemplates;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITemplateContentAppService), typeof(TemplateContentClientProxy))]
public partial class TemplateContentClientProxy : ClientProxyBase<ITemplateContentAppService>, ITemplateContentAppService
{
    public virtual async Task<TextTemplateContentDto> GetAsync(GetTemplateContentInput input)
    {
        return await RequestAsync<TextTemplateContentDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetTemplateContentInput), input }
        });
    }

    public virtual async Task RestoreToDefaultAsync(RestoreTemplateContentInput input)
    {
        await RequestAsync(nameof(RestoreToDefaultAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RestoreTemplateContentInput), input }
        });
    }

    public virtual async Task<TextTemplateContentDto> UpdateAsync(UpdateTemplateContentInput input)
    {
        return await RequestAsync<TextTemplateContentDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateTemplateContentInput), input }
        });
    }
}
