apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: elasticsearch
      port: 9200
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}