// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.Quartz.Histories;
using X.Abp.Quartz.Histories.Dtos;

// ReSharper disable once CheckNamespace
namespace X.Abp.Quartz;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IExecutionHistoryAppService), typeof(ExecutionHistoryClientProxy))]
public partial class ExecutionHistoryClientProxy : ClientProxyBase<IExecutionHistoryAppService>, IExecutionHistoryAppService
{
    public virtual async Task<PagedResultDto<ExecutionHistoryDto>> GetListAsync(GetExecutionHistoryListInput input)
    {
        return await RequestAsync<PagedResultDto<ExecutionHistoryDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetExecutionHistoryListInput), input }
        });
    }
}
