// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.Identity;

// ReSharper disable once CheckNamespace
namespace X.Abp.Identity;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentitySessionAppService), typeof(IdentitySessionClientProxy))]
public partial class IdentitySessionClientProxy : ClientProxyBase<IIdentitySessionAppService>, IIdentitySessionAppService
{
    public virtual async Task<PagedResultDto<IdentitySessionDto>> GetListAsync(GetIdentitySessionListInput input)
    {
        return await RequestAsync<PagedResultDto<IdentitySessionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetIdentitySessionListInput), input }
        });
    }

    public virtual async Task<IdentitySessionDto> GetAsync(Guid id)
    {
        return await RequestAsync<IdentitySessionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task RevokeAsync(Guid id)
    {
        await RequestAsync(nameof(RevokeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
