// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.Chat.Users;

// ReSharper disable once CheckNamespace
namespace X.Abp.Chat.Users;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IContactAppService), typeof(ContactClientProxy))]
public partial class ContactClientProxy : ClientProxyBase<IContactAppService>, IContactAppService
{
    public virtual async Task<List<ChatContactDto>> GetContactsAsync(GetContactsInput input)
    {
        return await RequestAsync<List<ChatContactDto>>(nameof(GetContactsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetContactsInput), input }
        });
    }

    public virtual async Task<int> GetTotalUnreadMessageCountAsync()
    {
        return await RequestAsync<int>(nameof(GetTotalUnreadMessageCountAsync));
    }
}
