// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.Chat.Conversations;
using X.Abp.Chat.Messages;

// ReSharper disable once CheckNamespace
namespace X.Abp.Chat.Conversations;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IConversationAppService), typeof(ConversationClientProxy))]
public partial class ConversationClientProxy : ClientProxyBase<IConversationAppService>, IConversationAppService
{
    public virtual async Task<ChatMessageDto> SendMessageAsync(SendMessageInput input)
    {
        return await RequestAsync<ChatMessageDto>(nameof(SendMessageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SendMessageInput), input }
        });
    }

    public virtual async Task<ChatConversationDto> GetConversationAsync(GetConversationInput input)
    {
        return await RequestAsync<ChatConversationDto>(nameof(GetConversationAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetConversationInput), input }
        });
    }

    public virtual async Task MarkConversationAsReadAsync(MarkConversationAsReadInput input)
    {
        await RequestAsync(nameof(MarkConversationAsReadAsync), new ClientProxyRequestTypeValue
        {
            { typeof(MarkConversationAsReadInput), input }
        });
    }

    public virtual async Task DeleteMessageAsync(DeleteMessageInput input)
    {
        await RequestAsync(nameof(DeleteMessageAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DeleteMessageInput), input }
        });
    }

    public virtual async Task DeleteConversationAsync(DeleteConversationInput input)
    {
        await RequestAsync(nameof(DeleteConversationAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DeleteConversationInput), input }
        });
    }
}
