// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.Chat.Settings;

// ReSharper disable once CheckNamespace
namespace X.Abp.Chat.Settings;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISettingsAppService), typeof(SettingsClientProxy))]
public partial class SettingsClientProxy : ClientProxyBase<ISettingsAppService>, ISettingsAppService
{
    public virtual async Task SetSendOnEnterSettingAsync(SendOnEnterSettingDto input)
    {
        await RequestAsync(nameof(SetSendOnEnterSettingAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SendOnEnterSettingDto), input }
        });
    }

    public virtual async Task<ChatSettingsDto> GetAsync()
    {
        return await RequestAsync<ChatSettingsDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(ChatSettingsDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ChatSettingsDto), input }
        });
    }
}
