apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: docker.elastic.co/kibana/kibana:7.10.2
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
          - name: kibana
            containerPort: 5601
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "{{ .Values.config.elasticsearchUrl }}"