config:
    selfUrl: # https://myprojectname-st-product
    corsOrigins: #
    connectionStrings:
        productService: #
        administrationService: #
        saasService: #
    authServer:
        authority: # http://myprojectname-st-authserver
        requireHttpsMetadata: # "false"
        swaggerClientId: WebGateway_Swagger
    dotnetEnv: Staging
    redisHost: #
    rabbitmqHost: #
    elasticsearchUrl: #
    stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
    host: myprojectname-st-product
    tlsSecret: myprojectname-tls

image:
    repository: mycompanyname/myprojectname-service-product
    tag: latest
    pullPolicy: IfNotPresent

env: {}
