// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using X.Abp.AuditLogging;

// ReSharper disable once CheckNamespace
namespace X.Abp.AuditLogging;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAuditLogSettingsAppService), typeof(AuditLogSettingsClientProxy))]
public partial class AuditLogSettingsClientProxy : ClientProxyBase<IAuditLogSettingsAppService>, IAuditLogSettingsAppService
{
    public virtual async Task<AuditLogSettingsDto> GetAsync()
    {
        return await RequestAsync<AuditLogSettingsDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(AuditLogSettingsDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AuditLogSettingsDto), input }
        });
    }

    public virtual async Task<AuditLogGlobalSettingsDto> GetGlobalAsync()
    {
        return await RequestAsync<AuditLogGlobalSettingsDto>(nameof(GetGlobalAsync));
    }

    public virtual async Task UpdateGlobalAsync(AuditLogGlobalSettingsDto input)
    {
        await RequestAsync(nameof(UpdateGlobalAsync), new ClientProxyRequestTypeValue
        {
            { typeof(AuditLogGlobalSettingsDto), input }
        });
    }
}
